### ISSUE TITLE
DevSeed orange

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/dirty-reprojectors-app#14]
Probably should be using DevSeed orange: `#cf3f02`

**Comment by DylanMoriarty** [comment]
That's by design, I thought the default DS orange was a bit too dark on the black background. As this is built by us and not an extension of our website, I don't think it's necessary to match it.

**Current:**
<img width="1273" alt="screenshot 2016-12-08 12 50 45" src="https://cloud.githubusercontent.com/assets/9341928/21021068/03ae68dc-bd45-11e6-9055-eb6246826977.png">

**DS Orange:**
<img width="1266" alt="screenshot 2016-12-08 12 50 34" src="https://cloud.githubusercontent.com/assets/9341928/21021064/ff0f3fd6-bd44-11e6-9ed4-81a04558a4b7.png">
